version: '3'
services:
#    db:
#        image: postgres
#        environment:
#            POSTGRES_PASSWORD: "@pineapple2020"
#        ports:
#            - "5432:5432"
#        networks:
#            - postgres-network

#    pgadmin:
#        image: dpage/pgadmin4
#        environment:
#            PGADMIN_DEFAULT_EMAIL: "christianoliveirati@gmail.com"
#            PGADMIN_DEFAULT_PASSWORD: "@pineapple2020"
#        ports:
#            - "8080:80"
#        networks:
#            - postgres-network

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "80:8000"
#        links:
#            - db

#networks: 
#    postgres-network:
#        driver: bridge